name: "My Docker Action"
description: "A GitHub Action that runs a shell script inside a Docker container"
author: "Chiyo Chan"

inputs:
  example-input:
    description: "An example input variable"
    required: false
    default: "World"

outputs:
  example-output:
    description: "An example output variable"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.example-input }}

branding:
  icon: "mic"
  color: "blue"
